name: kafka-connect-datagen
lang: java
lang_version: 17
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  extra_deploy_args: -Dcloud -Pjenkins
  extra_build_args: -Dcloud -Pjenkins
  generate_connect_changelogs: true
  run_maven_cve_scan: true
  run_pint_merge: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent.kafka.connect/kafka-connect-datagen
